spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: speer-assessment-DB
      uri: mongodb://localhost:27017/speer-assessment-DB
      username:
      password:
server:
  port: 9000

app:
  jwtSecret: mySecretKeyGeneratedSecurelySoPleaseDoNotTryToHackTheShitOutOfItAlsoletMeBeClearIamDoingThisOnlyToMakeThisStringVeryLongSoThatMyCodeDoesNotFailCAPEECE
  jwtExpirationInMs: 900000

logging:
  level:
    org:
      springframework:
        security: DEBUG

